package br.com.webinside.runtime.core;

public enum ExecuteParamsEnum {

	CLASSLOADER, HTTP_REQUEST, HTTP_RESPONSE, SERVLET_CONTEXT, OUT_STREAM, OUT_WRITER,
	WI_SESSION, WI_MAP, DATABASE_ALIASES, FILE_UPLOAD, PROJECT, PAGE, PRODUCER, ERROR_LOG;
	
}
